### ISSUE TITLE
Unable to compile the code of master branch in Ubuntu 14.04

### ISSUE THREAD

**Issue by Madity** [potree/PotreeConverter#130]
I am unable to compile the source code in Ubuntu 14.04. But the release version 1 is working fine in Ubuntu but the rendered images are only in black colour. When I used fix_fstream branch, it is giving segmentation fault during conversion.  

![screenshot from 2015-05-13 16 45 46](https://cloud.githubusercontent.com/assets/7779634/7609359/cf7d57a0-f98f-11e4-8761-d4eb344d0d5d.png)

**Comment by neteler** [comment]
Same issue on Fedora 21:

[ 76%] Building CXX object PotreeConverter/CMakeFiles/PotreeConverter.dir/src/PointAttributes.cpp.o
[ 84%] Building CXX object PotreeConverter/CMakeFiles/PotreeConverter.dir/src/PTXPointReader.cpp.o
/home/neteler/software/potreeConverter/PotreeConverter/src/PTXPointReader.cpp: In constructor ‘PTXPointReader::PTXPointReader(std::string)’:
/home/neteler/software/potreeConverter/PotreeConverter/src/PTXPointReader.cpp:83:18: error: use of deleted function ‘std::basic_fstream<char>& std::basic_fstream<char>::operator=(const std::basic_fstream<char>&)’
     this->stream = fstream(*(this->currentFile), ios::in);
                  ^
In file included from /home/neteler/software/potreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:0:
/usr/include/c++/4.9.2/fstream:779:11: note: ‘std::basic_fstream<char>& std::basic_fstream<char>::operator=(const std::basic_fstream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_fstream : public basic_iostream<_CharT, _Traits>
           ^
/usr/include/c++/4.9.2/fstream:779:11: error: use of deleted function ‘std::basic_iostream<char>& std::basic_iostream<char>::operator=(const std::basic_iostream<char>&)’
In file included from /usr/include/c++/4.9.2/fstream:38:0,
                 from /home/neteler/software/potreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:
/usr/include/c++/4.9.2/istream:795:11: note: ‘std::basic_iostream<char>& std::basic_iostream<char>::operator=(const std::basic_iostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_iostream
           ^
/usr/include/c++/4.9.2/istream:795:11: error: use of deleted function ‘std::basic_istream<char>& std::basic_istream<char>::operator=(const std::basic_istream<char>&)’
In file included from /usr/include/c++/4.9.2/fstream:38:0,
                 from /home/neteler/software/potreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:
/usr/include/c++/4.9.2/istream:58:11: note: ‘std::basic_istream<char>& std::basic_istream<char>::operator=(const std::basic_istream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_istream : virtual public basic_ios<_CharT, _Traits>
           ^
/usr/include/c++/4.9.2/istream:58:11: error: use of deleted function ‘std::basic_ios<char>& std::basic_ios<char>::operator=(const std::basic_ios<char>&)’
[...]

A fix would be appreciated.

**Comment by m-schuetz** [comment]
I've applied the patch mentioned here: https://github.com/potree/PotreeConverter/issues/115

Please check if the develop branch compiles now!

**Comment by anttiviljami** [comment]
It compiles as of 6dd4d664373808e5e33e58ec732d1e4d820b60d8 on Ubuntu 14.04. Please try the develop branch on your machine.
