### ISSUE TITLE
Upgrading to c++11 / c++14 ( Visual Studio 2015, gcc 4.8+)

### ISSUE THREAD

**Issue by m-schuetz** [potree/PotreeConverter#147]
VS2015 has support for some neat new c++11 features like
* user-defined literals
* defaulted functions
* initializer lists

and some more. Upgrading would defenitely break compatibility to VS2012 and VS2013, however.

**Comment by potree** [comment]
VS 2015 and gcc 4.9 also support some very nice c++14 features, more reason to upgrade! 
@sanak what kind of compiler are you using for osx?

**Comment by sanak** [comment]
I am using Xcode 6.4 on my Mac OSX (Yosemite) environment, and it seems to support c++14.
http://stackoverflow.com/questions/22952314/xcode-5-1-enable-c14

By the way, I sometime select Ubuntu 12.04 LTS as a server environment,
but I guess that it doesn't support c++14 because its released date is Apr, 2012...
So, I prefer c++11 for old environment compatibility.

**Comment by m-schuetz** [comment]
Ok, I'll make sure to target c++11 for the next release, at least.
What version of gcc are you using on your ubuntu 12.04 server?

**Comment by sanak** [comment]
The followings are Ubuntu recent LTS gcc versions.
* Ubuntu 12.04 LTS: gcc 4.6.3
* Ubuntu 14.04 LTS: gcc 4.8.2

**Comment by m-schuetz** [comment]
Upgrading done :)

From now on, gcc 4.9 and Visual Studio 2015 are required.
