### ISSUE TITLE
missing laszip dependencies

### ISSUE THREAD

**Issue by luxigo** [potree/PotreeConverter#158]
Hello,

Trying to build the the develop branch of PotreeConverter (after commit commit e395ef289b5e2eecdf61a64a6e08e6a8fad59cb0) under Debian 8.1 I have 
/src/PotreeConverter/PotreeConverter/include/LASPointReader.h:10:24: fatal error: laszip_dll.h: No such file or directory

After installing LASTools from freelasso and copying the missing header file in /src/PotreeConverter/PotreeConverter/include as workaround, the linker whine for missing library (only a dll is generated for laszip)

Thanks in advance :-)

**Comment by luxigo** [comment]
No better luck trying to link with https://github.com/LASzip/LASzip/releases/download/v2.2.0/laszip-src-2.2.0.tar.gz:

Missing laszip_create, laszip_request_compatibility_mode, laszip_open_reader, etc

**Comment by m-schuetz** [comment]
Just tried it on debian (i think it is 8.1, too).
One line in the lastools compile instruction was wrong. Instead of ```cd master``` it is ```cd master/LASzip```
Compiled and linked without problems after that. 

Have you also called ```make``` after ```cmake``` to compile laszip?

Have you tried using this fork of lastools? 
https://github.com/m-schuetz/LAStools
It contains cmake build files to generate the make files

> /src/PotreeConverter/PotreeConverter/include/LASPointReader.h:10:24: fatal error: laszip_dll.h: No such file or directory
Did you adapt the paths in the PotreeConverter cmake command?
-DLASZIP_INCLUDE_DIRS=~/dev/workspaces/lastools/master/LASzip/dll
This path should point to the directory of laszip_dll.h

**Comment by luxigo** [comment]
Oh sorry I did not rtfmd that you had updated, just looked for laszip_dll.h and tried LAStools from https://github.com/LAStools/LAStools and LASzip from Rapidlasso website :-) :8ball:

**Comment by luxigo** [comment]
thanks :-)
