### ISSUE TITLE
Build fails on linux

### ISSUE THREAD

**Issue by jeremyeastwood** [potree/PotreeConverter#228]
The linux build is now failing with the following error:

```/tmp/PotreeConverter/PotreeConverter/src/stuff.cpp:38:21: warning: extra tokens at end of #include directive
 #include <Windows.h>>
                     ^
/tmp/PotreeConverter/PotreeConverter/src/stuff.cpp:38:22: fatal error: Windows.h: No such file or directory
 #include <Windows.h>>
                      ^
compilation terminated.
make[2]: *** [PotreeConverter/CMakeFiles/PotreeConverter.dir/src/stuff.cpp.o] Error 1
make[1]: *** [PotreeConverter/CMakeFiles/PotreeConverter.dir/all] Error 2
make: *** [all] Error 2
```

the issue is also referenced in a comment to the latest merged pr (see https://github.com/potree/PotreeConverter/pull/226); I fixed by building from an older hash (ad452cfccdfdf38282f270ba9db4d8aa2ddac1a3), so looks like it's something that was introduced after that

**Comment by m-schuetz** [comment]
I've removed the duplicate > but on linux, you shouldn't get there at all since it's surrounded by a ```#ifdef BOOST_OS_WINDOWS``` check.
Is BOOST_OS_WINDOWS defined for you? Can you find out why?

**Comment by m-schuetz** [comment]
The relevant commit is this one here: https://github.com/potree/PotreeConverter/commit/b74f2cafa4b728cc2e28c7b2f8dc3a6731be223c

The problem was that before this commit, you had to call PotreeConverter from within its directory because it uses resources relative to that directory. After that commit, you can call PotreeConverter from any location because it loads resources relative to the executable. Finding the location of the executable is a surprisingly non-trivial thing and apparently led to this issue here.

**Comment by KentBrockman** [comment]
@m-schuetz Hey dude - did this issue get resolved?  The build process seems to work - just seem to be missing the PotreeConverter binary at PotreeConverter/build/PotreeConverter

**Comment by tbenoist** [comment]
Hi all,
Got the same problem (check for windows.h on linux)
AFAIK, the problem is in stuff.h 
it should be #if BOOST_OS_WINDOWS and not #ifdef 
Indeed, all BOOST_OS_XXXXs macros are always defined, but they evaluate to either a version on a supported platform or 0 when not applicable/supported.

Now with #ifdef changed to #if in stuff.h, I get a MAX_PATH undefined in stuff.cpp e.g. when defining char buffer[MAX_PATH]... any idea the value this should have?

**Comment by pierotofy** [comment]
The instructions provided by @tbenoist allowed me to compile PotreeConverter on linux. Had the same problem.

**Comment by adnan-wahab** [comment]
+1 @tbenoist 

that fixed it for me

**Comment by mastermwf** [comment]
I got it to build, but the html is empty. And yes I did copy the resources folder to the binary directory.
