### ISSUE TITLE
Struggling to get detail in final LOD

### ISSUE THREAD

**Issue by VanceOnTheInternet** [potree/PotreeConverter#245]
Hello,

I am attempting to upload a 6.5 billion point cloud and I am struggling to get the quality I am looking for. The point cloud is a combination of terrestrial laser scan data and photogrammetry data generated using PhotoScan. It was all imported into Cyclone, aligned, and exported out as one dataset. It is a large dataset attempting to digitally document petroglyphs, which are frequently only a few inches long, so the detail is important. I am using Potree 1.5RC

I have tried quite a few conversion settings starting with the basics:
PotreeConverter.exe d:\projects\2017_projects\lavabedspotree\Photogrammetry_Final_043017.pts -o d:\projects\2017_projects\lavabedspotree\potree_conversions\final\ -p combined_data -f xyzirgb

This gave me near the quality I was hoping for, and wrote 100% of the points, but point spacing wasn't quite close enough and was not uniform at the final level.

I have attempted to manually set the levels and spacing, but I have only got worse results:
`
c:\PotreeConverter_1.5RC_windows_64bit>PotreeConverter.exe D:\Projects\2017_Projects\LavaBedsPotree\Photogrammetry_Final_043017.pts -o D:\Projects\2017_Projects\LavaBedsPotree\potree_conversions\final3 --generate-page combined_data -f xyzirgb -s .5 -l 8`

My understanding is that the above settings should yield 8 LoDs, with a final level point spacing of around 2mm, but resulted in only 5 LoDs and roughly 6cm point spacing. Most of the LoDs seem to be spent on viewing from extreme distances. 

The latest attempt can be found [here](http://view3d.cast.uark.edu/petroglyphpoint/combined_data.html).

And here is the contents of the cloud.js file:

```
    "version": "1.7",
    "octreeDir": "data",
    "projection": "",
    "points": 1862476889,
    "boundingBox": {
        "lx": -374.268753,
        "ly": -150.593033,
        "lz": -2.77626,
        "ux": 356.381638,
        "uy": 580.057358,
        "uz": 727.874131
    },
    "tightBoundingBox": {
        "lx": -374.268753,
        "ly": -150.593033,
        "lz": -2.77626,
        "ux": 356.381638,
        "uy": 135.152145,
        "uz": 62.325241
    },
    "pointAttributes": [
        "POSITION_CARTESIAN",
        "COLOR_PACKED"
    ],
    "spacing": 0.5,
    "scale": 0.01,
    "hierarchyStepSize": 5
}

```

I have been struggling with this for a few weeks now and any insight would be greatly appreciated. I probably should have asked for help sooner!

**Comment by geotyr** [comment]
I am having a similar problem
instead of having a detailed hierchy I only get

`"hierarchyStepSize": 5`

in the cloud.js file, no information on hierarchy

how do I get something like that?
`	"hierarchy": [

		["r", 8376],

		["r0", 16089],

		["r2", 9061],

		["r4", 542],

		["r00", 10625],

		["r02", 9626],

		["r04", 5448],

		["r06", 2554],

                ...`
do I have to enter these levels manually in the js file?

I am guessing that the information should be in the r.hrc file but I don't how how to retrieve it
 the other option is that I running a previous version of potree (1.3) that took the hierarchy from the js file and that the current  version (1.8) takes it from the hrc files

That means that I have to update my potree version and convert again all the pointclouds that I have loaded (10, it is not that much for the moment)...or install the 1.3 version, but then I loose all the bug fixes.

Am I understanding everything correctly? what do you recommend?

thank you
