### ISSUE TITLE
r.hrc file not found

### ISSUE THREAD

**Issue by chyang0107** [potree/PotreeConverter#276]
Hi all,

I have a problem with the r.hrc file when I load a web page in the IIS through Windows server 2012 R2. I downloaded the 'PotreeConverter_1.5_windows_x64.zip' in my local machine (Windows 7) and then unzipped the file and converted ripple.las and generate a web page by the example provided. From the cmd image attached below, the points are generated. But, I could not see anything on the web page. I opened the r.hrc file by Notepad and only NUL displayed.

Could anyone provide your thoughts? 

Thanks,
Hank

![converter](https://user-images.githubusercontent.com/16352286/30922400-a5763c16-a36e-11e7-8841-76db8f93967c.jpg)

![rhrcfile](https://user-images.githubusercontent.com/16352286/30921312-d0d6cf86-a36b-11e7-8250-1059ca5fd7ea.jpg)

**Comment by fireballburning** [comment]
Hi,
I think I had the same problem and solved it by adding ".hrc" as a MIME Type of "application/octet-stream" for my IIS config. 
![image](https://user-images.githubusercontent.com/7087756/30980276-e0b94e42-a456-11e7-845c-e6244c2f89dd.png)
Since then Potree has working great in my local testing so far with IIS on Windows 10.  Maybe this IIS info could be added to the [Setup a Web-Server of the Getting Started page](https://github.com/potree/potree/blob/develop/docs/getting_started.md#setup-a-web-server) found in the Potree Repo?

**Comment by chyang0107** [comment]
Hi fireballburning,
I appreciate your suggestion. It is working like a charm! 

Hank
