### ISSUE TITLE
Pix4d .las

### ISSUE THREAD

**Issue by flightsurvey** [potree/PotreeConverter#297]
I am trying to convert a Pix4D .las file and it appears as a straight line. Does anyone know of conversion options that would address this?

Cheers

**Comment by m-schuetz** [comment]
That's likely because the coordinates are stored in lat/lon/height inside the las file. You're getting a line because lat/long are so much smaller than height.
You'll need to convert your las file to another las file in a uniform cartesian coordinate system with XYZ coordinates. Not sure how to do that but maybe there is an option in Pix4D to choose another coordinate system on export.

**Comment by flightsurvey** [comment]
Ok, thanks for getting back so swiftly.

**Comment by flightsurvey** [comment]
It must be posible as the Eclepens example states that the source data is from Pix4D - http://potree.org/showcase/eclepens.html. Any chance of talking to the person who submitted it to the gallery?

**Comment by m-schuetz** [comment]
That was me, I've got the las from Pix4D already in the right coordinate system.

**Comment by vvovvo** [comment]
We had the same issue while working with the New York Post Sandy dataset. We solved it by using FME to convert the data from lat/lon the correct projected coordinate system. If you don't have FME, I guess liblas can also do the conversion (see --t_srs https://www.liblas.org/utilities/las2las.html). 

    On Friday, 22 December 2017, 15:20, Flight Survey Ltd <notifications@github.com> wrote:
 

 It must be posible as the Eclepens example states that the source data is from Pix4D - http://potree.org/showcase/eclepens.html. Any chance of talking to the person who submitted it to the gallery?—

**Comment by flightsurvey** [comment]
Cheers all.

**Comment by flightsurvey** [comment]
vvovvo - I've just had a look at las2las. I don't suppose that you could help me a little bit further by telling what the parameters for the --t_srs conversion should be if you know? Cheers

**Comment by flightsurvey** [comment]
I've installed las2las according to the directions but when I run it fails saying that one or other dll could not be found. Tried any number of times to reinstall but it's not playing ball. I wonder if Windows 10 is an issue?

**Comment by vvovvo** [comment]
You can use an EPSG spatial reference ID for --t_srs. The exact SRID depends on the geo-location of your dataset.  Below is the command I used to re-project the New York Post Sandy data. Here are the screenshots of the data before and after the transformation.
las2las -v 20140326_usgsnyc14_18TWK790955.las 20140326_usgsnyc14_18TWK790955_reprojected.las --offset 277000,33000,0 --scale .01 .01 .01 --a_srs EPSG:4269 --t_srs EPSG:32118
As per the liblas installation, I cannot help since I am on Linux. 

    On Friday, 22 December 2017, 17:37, Flight Survey Ltd <notifications@github.com> wrote:
 

 I've installed las2las according to the directions but when I run it fails saying that one or other dll could not be found. Tried any number of times to reinstall but it's not playing ball. I wonder if Windows 10 is an issue?—

**Comment by flightsurvey** [comment]
Hi, I'm sorry but I have only just seen this - thank you very much for getting back. I'll give it a try.

**Comment by bfreed** [comment]
I'm sure I'm too late to help flightsurvey, but for anyone else who lands here:
You should set up the output coordinate system in Pix4D to be a projected coordinate system.
Instructions here: https://support.pix4d.com/hc/en-us/articles/205294205-Step-2-Creating-a-Project-4-Selecting-the-Output-GCP-Coordinate-System

In the US, the State Plane Coordinate System is usually a good bet, and the search function works well.
Example: Choose "Unit: **ft**", then check **Known Coordinate System**, then start typing your state name. Ex: "Penn" brings up a list for Pennsylvania. Stick with NAD83 and the appropriate part of the state.
Output will work great with PotreeConverter, we do it all the time.

**Comment by flightsurvey** [comment]
It's never too late and thank you very much for getting in contact. I'll let you know how I get on. Cheers.
