### ISSUE TITLE
EPSG:3857 distance increase 2x

### ISSUE THREAD

**Issue by winsento** [potree/PotreeConverter#339]
I have point.laz in EPSG:4326. With pdal reproject to EPSG:3857. In potree, the data looks slightly flattened and all measurements of the distance will be increased by 2 times.

**Comment by m-schuetz** [comment]
Could it be that your coordinates are stored in a mix of foot and meters?
Does your data look fine if you load it in cloud compare?

**Comment by winsento** [comment]
In CloudCompare  measurement result is the same as in the Potree. Here is original point.laz (EPSG:4326)  https://drive.google.com/file/d/1_e_cFMsHNYUBPkUgCAq3ZH-ypEgdlHAK/view

**Comment by m-schuetz** [comment]
I'm only getting a long line in Cloud Compare. There is very likely something off with the coordinate system you're using. Make sure all coordinates are euclidean coordinates in meters. Something like in the screenshot below usually happens if there is a mix between euclidean and polar coordinates. 

![image](https://user-images.githubusercontent.com/6705073/48018529-5b86ad00-e131-11e8-975e-f6842b7f1f02.png)

**Comment by winsento** [comment]
I looked at the data in GlobalMapper there everything is correct. I think the thing is reprojection in PDAL. Ticket until close.

**Comment by winsento** [comment]
@m-schuetz Yes, indeed, in the projection of EPSG:3857, distortions are observed and distances are incorrectly calculated. In a specific case, it was corrected by transfer to UTM, but it is not clear why this is so with EPSG:3857.

Briefly discussed it with @adamsteer here https://github.com/connormanning/entwine/issues/145#issuecomment-436568818

**Comment by adamsteer** [comment]
Do you have a screenshot from GlobalMapper for the points projected to EPSG:3857?

I got the same result as @m-schuetz  from the downloaded point cloud in Cloudcompare. Doing a straight conversion to EPSG:3857 got this:

![screen shot 2018-11-08 at 7 20 43 am](https://user-images.githubusercontent.com/13084118/48158543-ec72a980-e326-11e8-8d28-2dda825f6333.jpg)

…which leads to another suspicion - what about scaling X, Y and Z differently? 

You’re wanting to project from a polar XY (actually angles from an earth ‘centre’) system assuming metres ‘up’ from an ellipsoid, to a projected XY system assuming metres ‘up' from a sphere.

To set the scale(s) correctly you need to know something about the length of a degree in metres wherever you are - and you’ll need to add an offset in X and Y to keep numbers inside int32 (a LAS format limitation).

Having said that, I’m still not certain that’ll work out - but keen to see what you come up with!

**Comment by winsento** [comment]
ping @m-schuetz @connormanning

**Comment by connormanning** [comment]
Is there still a remaining question @winsento?  From what I could tell I thought this looked solved by using UTM as per @adamsteer's suggestion.

**Comment by winsento** [comment]
Yes UTM solves the problem. But it is not clear why EPSG: 3857 is such a result.

**Comment by connormanning** [comment]
It's because EPSG:3857 (web mercator) does not preserve distance/size, especially as you go further from the equator.  For example, these circles are the same size in reality but look distorted in EPSG:3857 (source [here](https://thatsmaths.com/2015/05/28/maps-on-the-web/)):

![mercator-tissot](https://user-images.githubusercontent.com/5015470/48163609-c35e0480-e2a5-11e8-8ab5-b523289f1e74.jpg)

For example, in ECEF (EPSG:4978) whose units are undistorted and in meters, your measurement comes out to 3.33 meters as you confirmed in the other thread:
![circle-ecef](https://user-images.githubusercontent.com/5015470/48164536-631c9200-e2a8-11e8-81c5-1c6fa35c5071.jpg)



In Potree's map on the EPSG:3857 version, you can see that your longitude is approximately 56.11°, about 0.979 radians.  The distortion ratio in EPSG:3857 can be calculated as `1 / cos(latitude)` (see [here](https://gis.stackexchange.com/questions/184648/whats-the-accuracy-of-web-mercator-epsg3857/184665#184665) and the [wikipedia entry](https://en.wikipedia.org/wiki/Mercator_projection#Mathematics_of_the_projection)).

For you, that's `1 / cos(latitude) = 1 / cos(0.979) = 1.793`.  So you'd expect the web mercator size distortion to increase your distance measurements by that factor: `3.33 * 1.793` = `5.971` units.  The web mercator measurement backs this up:
![circle-merc](https://user-images.githubusercontent.com/5015470/48164540-6879dc80-e2a8-11e8-8713-e4b4c4eb0449.jpg)

Web mercator is simply not suitable for direct distance measurements.  A distance of length 1 in web mercator only corresponds to 1 meter if you are on the equator.

**Comment by adamsteer** [comment]
@connormanning you’re completely on point here - thanks for doing the homework

**Comment by winsento** [comment]
@connormanning I had an assumption that the distortion is proportional to the inverse cosine of latitude. Many thanks for the detailed description.
