### ISSUE TITLE
Incremental conversion

### ISSUE THREAD

**Issue by elunty** [potree/PotreeConverter#342]
So i have a question about incremental conversion. In the readme it says this:

```
# first, convert with custom bounding box and then append new_data.las afterwards.
# points in new_data MUST fit into bounding box!
./PotreeConverter.exe C:/data -o C:/potree_converted -aabb "-0.748 -2.780 2.547 3.899 1.867 7.195"
./PotreeConverter.exe C:/new_data.las -o C:/potree_converted --incremental
```

Does that mean that you must strictly respect the bounding box only if you specify it the first time, or do you also have to respect the bounding box when it is automatically generated for you.

I can understand why it would be required to fall within the bounding box (the entire octree is useless if the new data exists outside those bounds), but i'm thinking maybe that you pull the data from the old tree first and create a new tree using the combined bounding boxes of both files.

**Comment by HTLife** [comment]
Any response to this question?

**Comment by midnight-dev** [comment]
Hi there. First, let me give you a disclaimer before anything else... 

It looks like Markus closed this after the new major version debuted. This option only applies to pre-2.0 release, so it may not be supported going forward, or it could be reimplemented in a different way. It's up to the creator. That said, PC 1.6/1.7 conversions are currently compatible with Potree JavaScript and Desktop applications, so on to the actual answer: 

The incremental option demands that any new points fit within the initial bounding box that the conversion used. Whether it was automatically determined or set manually should not matter. I don't actually know how common this would be for typical users, but say you started with a rough, low-density point cloud and you wanted to be able to add further detail as engineers sent it your way. The converter can add these points to your existing conversion because they're within the same space; there's just more of them for better detail and accuracy. Conversely, if the new points are outside the root AABB, I think the converter will complain (regardless of manual or automatic values). If you want to add distinct _chunks_ of a point cloud which don't share a root bounding box, you can ask the converter to take multiple input files in order to create a unified conversion. I haven't put this to the test, so your mileage may vary. Consult the program's help text if you run into trouble.
