### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by github-005** [potree/PotreeConverter#368]
![Screenshot from 2019-08-27 12-54-45](https://user-images.githubusercontent.com/48317959/63750263-c4126680-c8ca-11e9-94b7-f1c534d3c555.png)

**Comment by github-005** [comment]
please help to solve the problem = Segmentation fault (core dumped)

**Comment by ronykalfarisi** [comment]
I believe this is caused by wrong GCC/G++ version.

**Comment by eric-schleicher** [comment]
Hmm...  Is this because 'modern' Ubuntu installations no longer have 4.9?  It's fairly straightforward to get 4.8 (but lacks required c++14), buy extremely difficult to get 4.9 on 18.04

is there a range of gcc that work?  ubuntu 18.04 has 5.5, 6.4 7.4, 8.3...

What's involved in bringing it to a point where we don't have to use windows?
