### ISSUE TITLE
Indexing Crashes  - PotreeConverter 2.0

### ISSUE THREAD

**Issue by smcavoy12** [potree/PotreeConverter#427]
Potree 2.0 seems to failing a lot processing different datasets. No error is returned, the process just stops and exits. I'm changing my original post, i thought it had to do with structured data grids, but it'd having trouble on lots of other samples I'm running, regardless of format. 

I've attached a test cube in laz format, 300x300x300 meters with each point spaced exactly 1 meter apart. 
[cube.zip](https://github.com/potree/PotreeConverter/files/5099675/cube.zip)

Below is a version processed with 1.7
https://pointcloud.ucsd.edu/cube.html

also attaching log. gets to 98% indexing. 
[cube_log.txt](https://github.com/potree/PotreeConverter/files/5100635/cube_log.txt)

**Comment by lcrumbliss** [comment]
I too am experiencing a sudden program exit during the indexing phase of a large .las file (1.1 Billion points).  I am trying 2.0 because 1.7 is calculated to take weeks to process the same las file.

**Comment by m-schuetz** [comment]
Thanks for the reports, I'll take a look at it.

@lcrumbliss  
Would it be possible for you to also send me a laz file to mschuetz@potree.org?

**Comment by m-schuetz** [comment]
@smcavoy12

Problem is that the converter wasn't made with volume data in mind. The crash is caused because the subsampling array [has a fixed size of 1 million points](https://github.com/potree/PotreeConverter/blob/5dd6a120804972c03793c3265289269c82b57859/Converter/include/sampler_poisson.h#L109) and it is populated by access via an index (=number of already accepted points) [which causes an out of range error here](https://github.com/potree/PotreeConverter/blob/5dd6a120804972c03793c3265289269c82b57859/Converter/include/sampler_poisson.h#L211). I'm currently testing a fix to the crashes, but it will nevertheless perform rather poorly if the space is completely filled with points. May I ask, what is your use case? Even if the structure is built, it's not particularly suitable for rendering volume data.

**Comment by m-schuetz** [comment]
@smcavoy12 
Addressing the mentioned issue fixes the crash, but now the converter runs forever. I'll have to take a deeper look into that issue.

@lcrumbliss
Your issue might be a different one so if you can, send me a test data set that I can use to replicate and debug the issue.

**Comment by lcrumbliss** [comment]
@m-schuetz 
I will convert the las file to an laz file in LASTools.  Then I'll email you some log-in credentials to our extranet where you can download the file from.  Does that sound OK?

**Comment by m-schuetz** [comment]
Sounds good!

**Comment by lcrumbliss** [comment]
@m-schuetz 
OK.  Will take a while to convert to a laz file.  I will email you once everything is ready.

**Comment by lcrumbliss** [comment]
@m-schuetz 
OK, account created and email with instructions sent.

**Comment by m-schuetz** [comment]
thanks, I'll be looking at it as soon as possible

**Comment by m-schuetz** [comment]
@lcrumbliss 
There are a couple of issues here, one of which is that the bounding box is 1000x larger than it should be. It looks like almost the entire data set is within a box of size [400, 400, 177], but according to the las header the bounding box has a size of roughly [783370, 130523, 400]. Some subregions are able to be converted, like min: [1, 1, -2], max: [2, 2, 2], but the converter still crashes if the region covers the 400/400/177 size bounding box. 

I'll do some futher debugging in the next days. However, the bounding box has to be fixed because the converter as well as the renderer rely on meaningful bounding boxes. If the bounding box is too large by a factor 1000x, it would essentially lead to 10 virtually empty octree levels.

**Comment by lcrumbliss** [comment]
@m-schuetz 
Thanks Markus.  Yeah, I was coming to suspect that bounding cube.  Seriously, it was like 150 miles x 150 miles.  Thanks for taking a look.

**Comment by m-schuetz** [comment]
@dpfaff99

Sorry, I missed that, checking it right now.

**Comment by m-schuetz** [comment]
@dpfaff99 

Your file contains a large number of duplicate points. This will mess with the converter because it further partitions the octree based on the number of points in a node, but if all the points have the same coordinate, the converter keeps on partitioning without success, until it crashes.

I've comitted a "fix" that prints a warning and aborts further recursive partitioning, of a partition is just as large as the input: https://github.com/potree/PotreeConverter/commit/71cc41300d776b4cdeeba6dcbef198d9f0826fb7

This isn't a proper fix, however, and more of a hint that the las file needs to be repaired.

**Comment by m-schuetz** [comment]
Actually, I think I'm going to change this so that Potree aborts with an error rather than ignoring the issue and printing a warning.

**Comment by m-schuetz** [comment]
PotreeConverter now throws an error message like this:

```
ERROR(C:\dev\workspaces\PotreeConverter\2.0\Converter\src\indexer.cpp:904): a non-partitionable sequence of points was encountered, which may be caused by a large number of duplicates. #points in box: 12879, #unique points in box: 1, min: -3.16762, 0.155353, -0.172638, max: -3.16238, 0.160591, -0.1674
```
