### ISSUE TITLE
High memory usage with unordered point clouds

### ISSUE THREAD

**Issue by m-schuetz** [potree/PotreeConverter#43]
If consecutive points are all over the place instead of close together, PotreeConverter needs a lot of memory because it has to keep all nodes in memory.
As a workaround, it is possible to split the point cloud in tiles (with lastile, for example) and convert all the tiles instead. In one case this brought memory usage down from >15Gb to 1Gb.

PotreeConverter should be able to handle such unordered datasets by itself, for example by reading a chunk of points, sorting the chunk and then do the conversion.

**Comment by cnyinfei** [comment]
I read the code, and found that Convert uses a lot of cells to contain points and compare the distance between points. I'd say the sparse grid is a good idea. but why the cell size uses a value equal to "spacing"? That results almost all the cells contain only one point. I tracked the convert flow in debug mode and confirmed this.
The size of a GridCell is 72. Each may have 26 neighbors. Each neighbor pointer is 4 bytes(8 bytes in 64-bit binary). A point is 40 bytes. So each cell uses 200+ bytes to contain one point. That's a big waste!
So I modified the cell size to 10 times "spacing" in SparseGrid.cpp and got a much lower memory usage.

**Comment by potree** [comment]
Interesting. Did you get the same output results and was there a difference in conversion times?

**Comment by cnyinfei** [comment]
The outputs looks like the same. and the time usage slightly reduces. Need more performance test.

**Comment by cnyinfei** [comment]
I tried again. Same output results( at least seems "same"), 1/3 memory usage, 1/2 time usage.

**Comment by potree** [comment]
That sounds promising, I'll give it a try!

**Comment by m-schuetz** [comment]
Just tried one of my datasets and after the first 25m points the performance was just slightly better (~5%) but the memory consumption went down from 1.9GB to just 100mb. This is awesome! 
I'm going to experiment some more with this.

Thanks for this valuable suggestion!

**Comment by cnyinfei** [comment]
Further on, base on a larger cell size,  a cell contains more points, and SparseGrids have less nodes. Thus converter can use multi-thread to compute the minGaps.  OpenMP is a good choice,  very few code to modify, at least 2~3 times faster.

**Comment by m-schuetz** [comment]
Are there any significant advantages of using OpenMP over c++11 threads?

**Comment by m-schuetz** [comment]
Another possible optimization:
Since cells are much larger, distance to points in neighbouring cells don't have to be checked if the point isn't close to the cell boundary.

**Comment by cnyinfei** [comment]
The first benefit is easy to transplant the codes. Sometimes all you need is to add one compile directive, then you get faster speed. That's why I strongly recommend OpenMP.
By the way, I just tried a OpenMP version (modified GridCell::squaredMinGap to use OpenMP) but failed the test. It's much slower than origin converter. I think the problem is that each point updating cause a OpenMP multi-thread scheduler. I'd try some other methods to add the multi-thread support.

**Comment by cnyinfei** [comment]
Right. Even if not to use any multi-thread method. if GridCell ignore its neighbors, the performance can be greatly improved.

**Comment by chiccorusso** [comment]
I agree. I am experimenting with a version that completely ignores the neighborhood proximity check. Performance increase is about 3 times, without any visible difference in the rendered point cloud.

Experimenting with the SparseGrid cell size, I see a logarithmic decrease in memory usage and a small time decrease, with a minimum for a size of 6.

I tested the SparseGrid spacing only on one 47 million points scan.

But, using both the optimizations, the points at the cells frontier become denser (as expected due to the missing neighborhood proximity check) and the cells borders become visible.
Interesting that the neighborhood proximity check is superfluous if the SparseGrid spacing is 1.

![pandora_numbers](https://cloud.githubusercontent.com/assets/839405/8130142/685b8392-1110-11e5-8c02-014571c606f9.png)

**Comment by m-schuetz** [comment]
I've increased the cell size by 5 times and since the reduced memory usage allows it, points are now flushed after reading 5 instead of 1 million points. 

https://github.com/potree/PotreeConverter/commit/078e92b2037c069a04372f86d1d53c3040224f32

Together with the other performance improvements in the develop branch, the develop branch is now roughly 3 times faster than the PotreeConverter 1.1.1 release for one of the datasets I've tested.

**Comment by m-schuetz** [comment]
> But, using both the optimizations, the points at the cells frontier become denser (as expected due to the missing neighborhood proximity check) and the cells borders become visible.

The neighborhood check could probably be done only for points close to the cell border or if they're very close, they could be dismissed altogether (i.e. passed to the next level) in order to reduce the density at the border.

**Comment by cnyinfei** [comment]
<blockquote>
<p>But, using both the optimizations, the points at the cells frontier become denser (as expected due to the missing neighborhood proximity check) and the cells borders become visible.</p>
</blockquote>
Yes, this is proved in my tests. Neighbors can not be all ignored. But converter can skip most of them and directly pass to the next level.

<blockquote>
<p>Together with the other performance improvements in the develop branch, the develop branch is now roughly 3 times faster than the PotreeConverter 1.1.1 release for one of the datasets I've tested.</p></blockquote>
That sounds great!

**Comment by m-schuetz** [comment]
@cnyinfei
Could you send me your mail adress or send me a mail to mschuetz@potree.org ?
