### ISSUE TITLE
Installation on WIN 10

### ISSUE THREAD

**Issue by SebastianKasan** [potree/PotreeConverter#452]
I am trying to instal PotreeConverter on my Windows machine and I am struggling with this step:
![image](https://user-images.githubusercontent.com/39992733/93331300-4f390400-f820-11ea-87a0-3e500a159f9c.png)

Could you explain please how that is done? I don't find any documentation about how to "compile in release mode" in VStudio...

I tried to debug in release mode but I think that was probably the wrong thing to do...

![image](https://user-images.githubusercontent.com/39992733/93331443-87d8dd80-f820-11ea-83b7-0a03d5395a70.png)

**Comment by Ben29980** [comment]
Why, not using potree with command line : 
`C:/a/potree/PotreeConverter_1.6_windows_x64/PotreeConverter.exe C:/a/points.las -o C:/xampp/htdocs/potree --output-attributes CLASSIFICATION --material CLASSIFICATION --generate-page classificationtest`

**Comment by midnight-dev** [comment]
Hi Sebastian. The solution file is no longer part of the repo in favor of CMake. If you're using VS 2019 with most of the C++ features installed, you can easily compile everything correctly. Because the CMake lists are forcing release mode, you don't actually have to change the compile type. Just go to Build > Build All.

If you encounter an error, please respond with as much detail as you can.

**Comment by m-schuetz** [comment]
To compile in release mode, make sure the left dropdown on the menu above says "release", which it does in your case. Then right click the PotreeConverter project and chose compile. Since brotli was added, the solution explorer should look like this:
![image](https://user-images.githubusercontent.com/6705073/95063524-b864b680-06fe-11eb-90e6-4c3dd1d4b9c7.png)

But the easy way is to just download the precompiled windows binary here: https://github.com/potree/PotreeConverter/releases
