### ISSUE TITLE
Constantly loading in the viewer

### ISSUE THREAD

**Issue by Polak74** [potree/PotreeConverter#457]
Hi Markus,

I discovered a bug.
One of the files in the ZIP is constantly loading in the viewer, while the octree.bin is less than 100MB after a few minutes it exceeds the GB in the viewer.

https://gofile.io/d/dPgwYN

Is this a viewer or converter bug?

**Comment by Polak74** [comment]
Hi Markus,
Have you try it ?

**Comment by AlbionS** [comment]
Hi Markus and Polak,

I have the same problem. I have a las file without a color only with intensity. I use pdal (filters.python) to scale the intensity to color. With the PotreeConverter 1.7 this work fine but with the PotreeConverter 2.0 the loader in the viewer is constantly loading it,. 

If i just convert the las file without touching it with pdal, it works fine. Is it possible that pdal is adding some attributes to the las file that Potree 2.0 does not support 
?

**Comment by m-schuetz** [comment]
Thanks for the report. For some reason, some nodes have numPoints > 0 but byteOffset and byteSize = 0. I'll take a closer look at that bug tomorrow.

**Comment by Polak74** [comment]
Possible to fix the bug ?

**Comment by m-schuetz** [comment]
Yeah, but still looking at it. Using the latest version of the converter and potree (compression branches), Potree doesn't load the octree constantly, but the "bad" file still results in some strange precision issues.

**Comment by Polak74** [comment]
Hi Markus,
Fixed !
We are going to do some more testing!
Thank you for your responsiveness.

**Comment by m-schuetz** [comment]
Great!

**Comment by Polak74** [comment]
Hi Markus !

We discovered with this new converter, a random problem, depending on the clouds or the PC viewer.

However :
Chrome latest version
graphics card driver also.

The nodes are well downloaded, we can see the network activity, but no point cloud appears.

I don't know how to reproduce the problem for you.

**Comment by Polak74** [comment]
https://gofile.io/d/zQxj0N

An example, perhaps in file you can find solution, check on differente pc to reproduce error

**Comment by midnight-dev** [comment]
@Polak74 This is going to be partly questions and partly troubleshooting - my apologies if it's not that helpful. 

Could you clarify if you mean you don't see a rendering of the point clouds or if entries are also missing in Potree's scene menu? Can you confirm that this behavior _does not_ occur with an earlier version pairing of the converter & viewer (e.g. 2.0.1 & 1.7.1 respectively)? When you say it depends on the point cloud or viewer PC, does that mean that
- your clouds always work on one machine but not others, 
- your conversions either work or don't work and the effect is the same across every machine, or
- sometimes a converted cloud will work or not work, at random, regardless of the machine? 

If you can still see the point cloud name in the scene menu, ensure that it is checked (enabled), double click on it to see if the viewer zooms to a new location, and change the active attribute so you can see if the point cloud shows up when coloring the points differently, like with elevation or intensity gradients instead of RGBA. Check if you have high quality splats or Eye Dome Lighting enabled in the appearance menu; if so, disable EDL and switch to standard quality. Many mobile systems like phones, tablets, and Chromebooks will not render the points at all when these features are used because of an oversight in their WebGL extension compatibility. By the way, since we recently learned that Chrome doesn't like to render EDL/HQ when hardware acceleration is disabled, please make sure you have this turned on and running a modern-ish GPU - or just use Firefox since it doesn't suffer from this problem. Lastly, it would be really weird for this to be the case, but make sure the point cloud material opacity isn't set to something really low like 0 or 0.1.

**Comment by FrenchTrott** [comment]
Hi,
The right answer is sometimes a converted cloud will work or not work, at random, regardless of the machine.

The point cloud is right in scene menu and if i double click zoom in is correct but nothing in render, but network work good.

In same scene 1.7.2, i can have 2 point cloud, one with 2.0.0 and 2.0.2, but the file convert with 2.0.2 sometime not render....

but it can work on other machines.

**Comment by midnight-dev** [comment]
Could you please upload a small sample to something like Google Drive or Dropbox and share the link here? I'd need a known problematic file, and when I went to the previous link, the website said there was no download.

Perhaps looking for console errors or debugging the JavaScript is necessary here.

By the way, does this also happen in Firefox?

**Comment by FrenchTrott** [comment]
https://gofile.io/d/zQxj0N

**Comment by FrenchTrott** [comment]
Same on FireFox

**Comment by midnight-dev** [comment]
@FrenchTrott I can confirm that I'm seeing what you described. The point cloud isn't being rendered as expected. The ranges are indeed being called and downloaded when the view changes or when the point budget changes. Changing the attributes and disabling EDL has no effect.

I've stepped through the JavaScript, and it doesn't look like the 0 byte issue is at play here. I couldn't find a direct cause here when I was poking it yesterday. I'm going to give it another go tonight. The metadata has a few different values between the good and bad point clouds, but I'm not sure that's to blame. Do you remember what CLI arguments you passed to the converter to get these different conversions?

**Comment by FrenchTrott** [comment]
@minuit-dev thanks to reply

of memory none, no particular parameter.

Is Markus reading this issue since it is closed !?

**Comment by potree** [comment]
> Is Markus reading this issue since it is closed !?

I'm glancing at all new posts (getting mails), just don't always have time to respond right away. I'll try to find time to look at this issue today. 

> The right answer is sometimes a converted cloud will work or not work, at random, regardless of the machine.

At random sounds bad. Any way to reliably reproduce the error?

**Comment by FrenchTrott** [comment]
random sounds

I have been looking for 5 days but not found.
Maybe the problem comes from viewer 1.7.2

**Comment by FrenchTrott** [comment]
on the other hand, always on the same computers!

Thanks Markus !

**Comment by m-schuetz** [comment]
> @Polak74 https://gofile.io/d/zQxj0
> @FrenchTrott https://gofile.io/d/zQxj0N

First doesn't work, second does. Is second link just the fixed version of the first one or are they supposed to be two different ones?

In any case, the point cloud by @FrenchTrott works fine for me in PotreeDesktop, including the release at: https://github.com/potree/PotreeDesktop/releases/tag/1.7.2. No errors and everything seems to render as it should. 

> on the other hand, always on the same computers!

So on one PC it always works, and on another it never works? Are there any errors in the dev console (F12 or Ctrl+shift+i)?

**Comment by m-schuetz** [comment]
That's a bit tough to debug, then. Can you provide some more infos like:
* What's the last version that works? Does PotreeConverter 1.7 + Potree 1.7 work? PotreeConverter 1.6 with Potree 1.6?
* OS?
* What GPU?
* Do the demos at https://github.com/potree/potree/#examples work?

**Comment by midnight-dev** [comment]
I hate to be the bearer of bad news, but I can absolutely confirm what @FrenchTrott is experiencing. Originally, I thought the bugged point cloud might not work at all because I was only viewing it on my laptop, but I'm at work right now scratching my head because the point cloud is rendered on my workstation. Mostly. 

At first, it only renders as black points.
![potree_bugged_pc_1](https://user-images.githubusercontent.com/47105073/96182612-545ea100-0efb-11eb-9d21-bff128f3b248.png)

Clicking on the point cloud name under the Scene menu immediately selects intensity and its material can now be seen.
![potree_bugged_pc_2](https://user-images.githubusercontent.com/47105073/96182734-807a2200-0efb-11eb-99aa-1d467cd3a65a.png)

Changing the display attribute to RGBA gives it the (presumably) correct color.
![potree_bugged_pc_3](https://user-images.githubusercontent.com/47105073/96182847-aa334900-0efb-11eb-95c3-2123367fcdc9.png)

Meanwhile, on my laptop, clicking on the point cloud name & changing the display attribute does nothing. Double clicking makes the movement speed change, so it thinks its zooming to something, but nothing is rendered. It's like the frustum is getting messed up and everything is being culled. 

![image](https://user-images.githubusercontent.com/47105073/96183469-86bcce00-0efc-11eb-8e00-a93af8671d3e.png)


Activating measurements, e.g. point or volume boxes, seems to do nothing at first (no change to the render), but upon zooming out, this they appear out of nowhere.
![image](https://user-images.githubusercontent.com/47105073/96183556-a48a3300-0efc-11eb-9a05-a736151a0c65.png)

This has further piqued my interest. I'll continue investigating this, but for now I can't say why it renders on one machine and not the other. My laptop uses an Intel iGPU with a hybrid NVidia MX150 GPU, while the workstation has 3 monitors and 2 dedicated GPUs, and each monitor is 4K. When I shrunk the window size to less than 1080p, nothing changed. It still loads on my desktop, but not on my laptop. Anyway, this was just to give you guys an update. We still need to figure out how to reproduce this across machines and then find what is causing this mess.

**Comment by smcavoy12** [comment]
@midnight-dev 

If it's useful I'd be happy to serve that cloud publicly so it's easier for multiple people to try on different hardware.

**Comment by midnight-dev** [comment]
@smcavoy12 Much appreciated, Scott. I may have found something though. Not sure how much longer this will be relevant, but it's still curious why different machines handle this more gracefully than others. By the way, I forgot to mention in my earlier comment that even when the point clouds and measurements to appear, the bounding boxes are still properly rendered when that debug option is enabled. This may be irrelevant, but it's worth noting.

So on a whim, I compared the metadata JSON files and noticed the bugged version has a `gps-time` attribute while the working point cloud does not. Removing this allows my laptop to render black points like my desktop. I can't seem to get at the proper RGBA color that my workstation renders. It's still very dark if not black. The shaders for other materials like elevation and intensity work as expected, just not RGBA.

For documentation sake, this is the JSON of the `gps-time` attribute that's bugging out Potree 1.7.2, 1.7.1, and 1.7.0 on my laptop:

```json
{
	"name": "gps-time",
	"description": "",
	"size": 8,
	"numElements": 1,
	"elementSize": 8,
	"type": "double",
	"min": [0],
	"max": [0]
}
```

**Comment by midnight-dev** [comment]
Update:

You know how in programming, a single character can cause a lot of headache and frustration?

` "max": [1] `

![image](https://user-images.githubusercontent.com/47105073/96199575-7832de80-0f1d-11eb-8e12-31f26f0bafe7.png)

# ಠ_ಠ

Apparently, the renderer will flip out if the gps-time has a min and max that are equal. But only on some computers, I guess. It's better to not have the gps-time attribute at all if the min and max aren't different. It might be a race condition where some machines, like my office workstation, are faster than others at loading the data. It skips over whatever is causing trouble on my laptop. 

@Polak74 & @FrenchTrott Can you guys confirm whether or not the point cloud renders on faster machines? And also, to fix the render issue, open the metadata.json file and change the `"max"` property of the gps-time to be `[1]` instead of `[0]`. Hope this helps.

@m-schuetz If PDAL is adding this 0, 0 gps-time to point clouds, maybe core Potree should just skip adding the gps-time to the known attributes or fail gracefully when a 0, 0 min/max are discovered.

**Comment by FrenchTrott** [comment]
Hi all,
Hi @midnight-dev, and thanks.

I confirm that GPS is the cause.

My problematic file had this.

			"name": "gps-time",
			"description": "",
			"size": 8,
			"numElements": 1,
			"elementSize": 8,
			"type": "double",
			"min": [0],
			"max": [0]

And if i modify this to 

			"name": "gps-time",
			"description": "",
			"size": 8,
			"numElements": 1,
			"elementSize": 8,
			"type": "double",
			"min": [0],
			"max": [1]

File is render ...

but i find it hard to understand why some computers can render and others can't.

curious to understand.

**Comment by midnight-dev** [comment]
@FrenchTrott I don't know why either. I can only speculate that some computers finish extracting the `gps-time` a little sooner than others, and based on when the shaders get compiled, sometimes the points are rendered and other times they are not. 

That's why I was asking you if you notice slower computers having this problem. Two workstations at my office rendered the bugged point cloud as expected, but my laptop (much slower) would always fail. This is just a hunch. It deserves more attention at a later date, but for now we have a fix that _should_ work. If you're able, checkout potree/potree#909 to see if this works for you too. Let me know if there are still problems.
