### ISSUE TITLE
Command Line options

### ISSUE THREAD

**Issue by HeadLessHUN** [potree/PotreeConverter#463]
Hi there Finnaly i have a little time to try out the new converter it would be great if you had a command line option list or help maybe inside a the program as well.

I'd like to ask you how to convert multiple input files to one cloud withou merging them beforehands. I'm talking about a lot of clouds like 5 to 10 hundred scan location so it cannot fit to the 2047 character long command line limit. So the best way would be that to place the urls to a file ad then i can add that single file as a source...

I tried to search the incremental convert option, but for that i would have to find the global AABB matrix i think, and that takes long time.

**Comment by smcavoy12** [comment]
Hi, if list the directory as the input it'll process them all.

PotreeConverter C:/directory -o C:/converteddirectory

 I think there's a way to designate a file list too as input, . I can't seem to find that example. Something like this:

PotreeConverter C:/filelist.txt -o C:/converteddirectory --filelist

**Comment by potree** [comment]
2.0 doesn't have the list of files argument, but putting the files in a directory and specifying the directory as input should work. 
The 2047 character command line limit might be a specific command line application limit? I think I've called PotreeConverter with way more characters using [launch.json](https://github.com/potree/PotreeConverter/blob/develop/.vscode/launch.json). If you custom compile PotreeConverter and then open the project with vscode, you can execute the launch.json config with ctrl + F5. I'm almost always calling PotreeConverter like that because it's very convenient once it's set up.

**Comment by HeadLessHUN** [comment]
yes it is a batch script i don't have time to rewrite the whole converter subsampler script. i never run the same files always differents. the directory option can be easily made by script. thanks
