### ISSUE TITLE
Structured Data Potree 1.7 vs 2.2 (non-volumetric)

### ISSUE THREAD

**Issue by smcavoy12** [potree/PotreeConverter#480]
Hi Potree,

When processing voxelized non-volumetric pointclouds 2.2 causes some odd banding.

2 test pointclouds attached via google drive
https://drive.google.com/file/d/1AFMvCbuJpvktdiwK53M44h0A4LUzEEb-/view?usp=sharing

This video shows unstructured versions, and two voxelized at 1cm resolution all converted with 1.7 and 2.2
https://youtu.be/TWmwN7dRXro

1.7 handles it well enough (some adaptive point sizing issues), but 2.2 seems to lose points in a stripey pattern.
![banding](https://user-images.githubusercontent.com/13354749/100522906-1ba02180-3161-11eb-949c-3b455a4a0f77.PNG)

I realize potree is meant for unstructured data, and handles it very well, but if there's any chance of getting it to handle structured data it'd open us up to some really interesting applications

Thanks very much!

**Comment by midnight-dev** [comment]
That's pretty neat, but it would be a nightmare to debug due to point count - at least for me. 

Would you be able to crop out a large area in something like CloudCompare and verify the same banding occurs in 2.0.2 conversions?

To find weird behavioral patterns, incremental stepping is required, so anything above 100 points is prohibitively lengthy.

Oh, and this may or may not be relevant depending on point count, but do you know if the banding changes depending on chunking method?

**Comment by smcavoy12** [comment]
Hi Ben, I've tried with random/poisson and got the same result, but I wasn't even aware there were other chunking methods! I see we use LASzip standard, would you be able to point me to any documentation regarding the other chunking options?

Guess what! While preparing a 100 point tiled dataset in CloudCompare to give you the tiles had a similar problem! Apparently it's an issue applying the global offset (shift). When I resaved the laz without the offset it worked great:

![banding_offset](https://user-images.githubusercontent.com/13354749/100525409-7c395980-3175-11eb-98de-a6f7a2571798.PNG)

**Comment by midnight-dev** [comment]
Ah, thank you for checking & giving us a description. It may help people in the future. I have to correct myself: I should've said sampling method, not chunking method. 

For completeness sake, the sampling methods that Markus and research mates came up with are _Poisson_ (with a double s) and _random_.

You can change this by specifying `-m poisson` or `-m random` in your command. I believe Poisson is still the default.

The reason I meant to suggest this is because I remember some tests showing a visible difference way back when 2.0 had launched. Each method dictates where PotreeConverter will accept a point, and thus a pattern may become visible. For Poisson, later points in each node are judged by previously accepted points. The main factor to focus on is distance between points. Poisson tries to keep things neat and orderly by making sure the same space is kept among future points, so it can become _poissoned_ (yes, I amuse myself, too) if the first few points in a node are not ideal compared to the rest. If you notice odd lines or patterns in your conversions, this could be responsible. On the flip side, random combats this possible side effect by its very nature of being random; though this may not always render the most pleasing spacing to our eyes. By the way, random should be faster because distance doesn't have to keep being compared. 

I might have to post a wiki page about it since most people aren't going to download the research PDF about parallel point cloud conversions. It's an interesting read, though.
