### ISSUE TITLE
Sub-directory schema

### ISSUE THREAD

**Issue by dkastl** [potree/PotreeConverter#57]
Storing all data in a single directory might be at least inconvenient for large point clouds.
Having a standardized sub-directory schema could solve this issue. 

Standardization may also help to:

* Incrementally update/process levels
* Append additional data
* Have a smaller `cloud.js` file

For tile map services there exist already directory schema for quad-trees, which prevent to have too many files in a single directory.

* TileCache: http://svn.osgeo.org/tilecache/trunk/tilecache/TileCache/Caches/Disk.py
* GeoWebCache: https://github.com/GeoWebCache/geowebcache/blob/master/geowebcache/core/src/main/java/org/geowebcache/storage/blobstore/file/FilePathGenerator.java

**Comment by chiccorusso** [comment]
Hi. A simple patch should be enough to create a subdir schema in which files are grouped by the first and second digit (that would create a first subdirectory level) and by the third and fourth digit (that would create a second subdirectory level). Files from r to r77 would remain in the main directory.

On the client side there is the need to rewrite the search for the parent node name, because it could end with "/".

I can try something.

**Comment by m-schuetz** [comment]
Hi!

I've dones this very similarely now as part of the cloud.js filesize reduction.
I'm partitioning it in steps of 5 levels, though, the same as the hierarchy is beeing partitioned.
