### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by dkastl** [potree/PotreeConverter#59]
It could be interesting to do automated testing for "develop" branch and then run builds with Travis CI: https://travis-ci.org/

**Comment by cvvergara** [comment]
This is not a solution, but @sanak helped me to make an automated testing in my computer.
I have in my computer a directory with the lion and the the results of running the converter:
```
#[BIN]
./PotreeConverter lion_takanawa.las -s 0.15 -l 3 -o bin --output-format BINARY > stats/binStats.txt
#[LAS]
./PotreeConverter lion_takanawa.las -s 0.15 -l 3 -o las --output-format LAS > stats/lasStats.txt
```
this is the directory:
```
drwxr-xr-x 4 mapas users      4096 ago  2 21:49 bin
-rw-r--r-- 1 mapas users       552 ago  2 21:51 compare.sh
drwxr-xr-x 4 mapas users      4096 ago  2 21:12 las
-rw-r--r-- 1 mapas users  30030774 ago  20:55 lion_takanawa.7z        
-rw-r--r-- 1 mapas users 118397431 jun  3  2014 lion_takanawa.las
```
The compare.sh does the same convertions, but  I store in a different directory, and diff compare directories, I also diff compare all the statistics that come from the command.
```
# [BINARY]
./PotreeConverter lion_takanawa.las -s 0.15 -l 3 -o binTest --output-format BINARY > stats/binStatsTest.txt
#[LAS]
./PotreeConverter lion_takanawa.las -s 0.15 -l 3 -o lasTest --output-format LAS > stats/lasStatsTest.txt
#[LAZ]   -- doesnt work for ubuntu
#PotreeConverter lion_takanawa.las -s 0.15 -l 3 -o laz --output-format LAZ
echo comparing binary stats
diff stats/binStats.txt stats/binStatsTest.txt
echo comparing las stats
diff stats/lasStats.txt stats/lasStatsTest.txt

echo comparing BINARY
diff -bur bin binTest

echo comparing LAS
diff -bur las lasTest
```
this is a run I made to make sure that the for-loop didn't modify the output:
```
$ sh compare.sh 
comparing binary stats
28c28
< duration: 5.223s
---
> duration: 3.924s
comparing las stats
28c28
< duration: 4.973s
---
> duration: 4.032s
comparing BINARY
comparing LAS
```

(looks like it is a second faster... but if you really want to make an statistic of how much faster it is, more figures are needed and for each one at least 30 times needs to be executed under the same conditions, so that an average can be performed with a good degree of freedom and make a size / time relationship).

**Comment by cvvergara** [comment]
For travis:
For testing, the tiger is a very complicated figure, A test is to be thought as "for this input I expect this output".
With simpler figures like:
Cube, pyramid, cone, sphere, cylinder.
1) first its easier to check visually that the output is correct.
2) so we expect the same output when code changes
3) and a complex figure/map, 
It needs to be considered that everything goes to the repository so take into account the size.

The input: the figures: they can be stored in zip/tar
The expected output: its a directory and it can be zip/tar

The script that does the checking in travis:
 unzip/untar the input and output, 
runs the commands, 
does the comparison
prints out any difference.

**Comment by cvvergara** [comment]
From the code I can see that there are several conversion that can be done, right now I only have the 
las to las
las to binary
But all possible conversion combinations needs to be tested also
