### ISSUE TITLE
Data displaying in alternating rows

### ISSUE THREAD

**Issue by derricksharp** [potree/PotreeConverter#98]
I am converting a .las file to binary. The .las file is around 9 million points. I have tried many different configurations, but every time I view the file in Potree viewer there are bands of missing points in horizontal lines.It looks like 3 or 4 rows of points are not displaying. I've tried changing various settings in the viewer, and it appears that is has something to do with the conversion. What can I try?

Thanks,
Derrick

**Comment by m-schuetz** [comment]
Hello Derrick,

Can you show me a screenshot of your problem?
If you're seeing rows/lines of points with space in between, this is usually due to precision problems in the converted data. This shouldn't be happening with the newest version of the converter ( http://potree.org/downloads/PotreeConverter/PotreeConverter_2014.12.30.zip ) but who knows.

If you can, please send me a sample of your converted and original data to mschuetz@potree.org so I can take a closer look at it.
I'm traveling right now so replies may take a while.

**Comment by derricksharp** [comment]
I am using the latest version of the converter.
Here's a screen shot of what I'm seeing.

![image](https://cloud.githubusercontent.com/assets/6828515/6002929/9be0b2cc-aab4-11e4-9bce-75a2df5e5f86.png)

Thanks for your help!

**Comment by m-schuetz** [comment]
Ah, that might be another issue. Try to set the scale parameter for conversion:

```./PotreeConverter,exe data.las --scale 0.001 ```
 
Default for scale is 0.01 which gives a centimeter precision, assuming the coordinates are in meters. with 0.001 you'll get milimeter precision.

I'll have to modify the PotreeConverter to take over the spacing of the las file or calculate a meaningfull spacing according to the point clouds bounding box.

**Comment by derricksharp** [comment]
You're the man!

Changing the scale worked like a charm. 

![image](https://cloud.githubusercontent.com/assets/6828515/6003187/cebccfda-aab6-11e4-95c5-d4dbe20e4525.png)

Thanks!
